# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created: Fri Nov 14 17:23:52 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(800, 600)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.splitter = QtGui.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.verticalLayoutWidget = QtGui.QWidget(self.splitter)
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label = QtGui.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label)
        self.label_2 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout_2.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_3)
        self.w_triggerPV = QtGui.QLineEdit(self.verticalLayoutWidget)
        self.w_triggerPV.setObjectName(_fromUtf8("w_triggerPV"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.w_triggerPV)
        self.w_messagePV = QtGui.QLineEdit(self.verticalLayoutWidget)
        self.w_messagePV.setObjectName(_fromUtf8("w_messagePV"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.w_messagePV)
        self.emails = QtGui.QListView(self.verticalLayoutWidget)
        self.emails.setTabKeyNavigation(True)
        self.emails.setAlternatingRowColors(True)
        self.emails.setObjectName(_fromUtf8("emails"))
        self.formLayout_2.setWidget(5, QtGui.QFormLayout.FieldRole, self.emails)
        self.label_4 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_4)
        self.w_config_file_name = QtGui.QLabel(self.verticalLayoutWidget)
        self.w_config_file_name.setObjectName(_fromUtf8("w_config_file_name"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.w_config_file_name)
        self.label_5 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_5)
        self.w_messagePV_text = QtGui.QLineEdit(self.verticalLayoutWidget)
        self.w_messagePV_text.setObjectName(_fromUtf8("w_messagePV_text"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.FieldRole, self.w_messagePV_text)
        self.label_6 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_6)
        self.w_log_file_name = QtGui.QLabel(self.verticalLayoutWidget)
        self.w_log_file_name.setObjectName(_fromUtf8("w_log_file_name"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.w_log_file_name)
        self.verticalLayout_2.addLayout(self.formLayout_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.w_btn_run = QtGui.QPushButton(self.verticalLayoutWidget)
        self.w_btn_run.setObjectName(_fromUtf8("w_btn_run"))
        self.horizontalLayout.addWidget(self.w_btn_run)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.w_running_stopped = QtGui.QLabel(self.verticalLayoutWidget)
        self.w_running_stopped.setObjectName(_fromUtf8("w_running_stopped"))
        self.horizontalLayout.addWidget(self.w_running_stopped)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.w_btn_stop = QtGui.QPushButton(self.verticalLayoutWidget)
        self.w_btn_stop.setObjectName(_fromUtf8("w_btn_stop"))
        self.horizontalLayout.addWidget(self.w_btn_stop)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.gridLayout.addWidget(self.splitter, 0, 0, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.history = QtGui.QTextBrowser(self.groupBox)
        self.history.setObjectName(_fromUtf8("history"))
        self.gridLayout_2.addWidget(self.history, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setObjectName(_fromUtf8("menuEdit"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbout_pvMail = QtGui.QAction(MainWindow)
        self.actionAbout_pvMail.setObjectName(_fromUtf8("actionAbout_pvMail"))
        self.actionE_xit = QtGui.QAction(MainWindow)
        self.actionE_xit.setObjectName(_fromUtf8("actionE_xit"))
        self.actionSend_test_email = QtGui.QAction(MainWindow)
        self.actionSend_test_email.setObjectName(_fromUtf8("actionSend_test_email"))
        self.menuFile.addAction(self.actionSend_test_email)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionE_xit)
        self.menuHelp.addAction(self.actionAbout_pvMail)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "pvMail", None))
        self.label.setText(_translate("MainWindow", "trigger PV", None))
        self.label_2.setText(_translate("MainWindow", "message PV", None))
        self.label_3.setText(_translate("MainWindow", "email address(es)", None))
        self.label_4.setText(_translate("MainWindow", "config file", None))
        self.w_config_file_name.setText(_translate("MainWindow", "email configuration settings file name goes here", None))
        self.label_5.setText(_translate("MainWindow", "message text", None))
        self.w_messagePV_text.setText(_translate("MainWindow", "text from PV goes here", None))
        self.label_6.setText(_translate("MainWindow", "log file", None))
        self.w_log_file_name.setText(_translate("MainWindow", "log file name goes here", None))
        self.w_btn_run.setText(_translate("MainWindow", "Run", None))
        self.w_running_stopped.setText(_translate("MainWindow", "running | stopped", None))
        self.w_btn_stop.setText(_translate("MainWindow", "Stop", None))
        self.groupBox.setTitle(_translate("MainWindow", "History", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.actionAbout_pvMail.setText(_translate("MainWindow", "About pvMail", None))
        self.actionE_xit.setText(_translate("MainWindow", "E&xit", None))
        self.actionSend_test_email.setText(_translate("MainWindow", "send test email", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

